---
- hosts: jenkins
  become: yes
  tasks:
    - include: tasks/java21.yml
    - include: tasks/leiningen.yml
    - include: tasks/cypress-deps.yml


- hosts: jenkins
  vars:
    solita_jenkins_jobs_dir: jobs
    solita_jenkins_plugins:
      - timestamper
      - git
      - leiningen-plugin
      - slack
      - ansible
      - envinject
      - parameterized-trigger
      - nodejs
      - toolenv
      - xvfb
    solita_jenkins_security_realm: jenkins
    solita_jenkins_users:
      - tatut
      - markusva
      - markussak
      - tonida
      - villeliski
      - tommik
      - ernok
      - jonik
      - mattiu
      - antti.nuortimo
      - esko.suomi
      - oskari.jokinen
      - jaska.kivela
      - peetu.kaan
  roles:
    - solita.jenkins
