---

- name: Install OTE
  hosts: ote
  serial: 1
  max_fail_percentage: 1
  become: true
  tasks:
    - include: tasks/napote_group_and_user.yml
    - include: tasks/ote.yml
      vars:
        java_download_url: https://download.oracle.com/java/17/archive/jdk-17.0.3_linux-x64_bin.tar.gz
        java_download_folder: /opt
        java_version_path: jdk-17.0.3
        download_version: jdk-17
        java_name: "{{java_download_folder}}/{{java_version_path}}"
        java_archive: "{{java_download_folder}}/{{download_version}}_linux_x64.tar.gz"
