- name: Install jq
  yum: name=jq state=installed
  tags: hostsfile

- name: Enable codeready / EPEL repository
  command: subscription-manager repos --enable codeready-builder-for-rhel-9-$(arch)-rpms
  tags: hostsfile
  
- name: Install codeready / EPEL repository
  command: dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y
  tags: hostsfile

- name: Install awscli
  command: dnf --enablerepo=codeready-builder-for-rhel-9-rhui-rpms install awscli -y
  tags: hostsfile

- name: Copy hostfile generator
  copy: src=templates/genhosts.j2 dest=/etc/cron.hourly/genhosts owner=root group=root mode=0744
  tags: hostsfile
